### ISSUE TITLE
Coin Drop Crash

### ISSUE THREAD

**Issue by VanilaBOI** [ferreusveritas/Nomisma#1]
I'm running Nomisma on my Server and whenever a Zombie/Illiger would drop a coin it crashes the player but not the server.

**Comment by ferreusveritas** [comment]
Fixed.

**Comment by VanilaBOI** [comment]
Well thank you for getting back to me so quickly but I have good and bad news.
The good news is it doesn't crash any more but the bad news is I have spawned about a milion Zombies, Illigers and Witches and no drops with the config on.

**Comment by ferreusveritas** [comment]
You probably only spawned and killed those mobs in the same world location.  That's the anti-cheese feature doing it's thing.  In order to get coins you need to move around the world and kill those mobs.  Anti cheese can be disabled if you don't like this.
